# Generated by Django 6.1 on 2026-08-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificativo único para el escenario.', max_length=100, unique=True, verbose_name='Nombre del escenario')),
                ('ubicacion', models.CharField(blank=True, help_text="Descripción de la ubicación (ej. 'Zona Norte', 'Junto al lago').", max_length=200, verbose_name='Ubicación en el recinto')),
                ('capacidad', models.PositiveIntegerField(help_text='Número máximo aproximado de personas que caben en la zona del escenario.', verbose_name='Capacidad máxima')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Escenario',
                'verbose_name_plural': 'Escenarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Actuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día en el que se llevará a cabo el concierto.', verbose_name='Fecha de la actuación')),
                ('hora_inicio', models.TimeField(help_text='Hora a la que comenzará la actuación.', verbose_name='Hora de inicio')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, help_text='Duración estimada de la actuación en minutos.', verbose_name='Duración (minutos)')),
                ('descripcion', models.TextField(blank=True, help_text='Información adicional sobre la actuación o requerimientos técnicos.', verbose_name='Descripción / Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('artista', models.ForeignKey(help_text='Artista o grupo que actuará.', on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='artistas.artistas', verbose_name='Artista')),
                ('escenario', models.ForeignKey(help_text='Escenario donde tendrá lugar la actuación.', on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='actuaciones.escenario', verbose_name='Escenario')),
            ],
            options={
                'verbose_name': 'Actuación',
                'verbose_name_plural': 'Actuaciones',
                'ordering': ['fecha', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('escenario', 'fecha', 'hora_inicio'), name='unique_actuacion_mismo_escenario_fecha_hora')],
            },
        ),
    ]
